[package]
name = "rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
colored = "3.0.0"
sysinfo = "0.37.0"
terminal_size = "0.4.3"
walkdir = "2.5.0"
